import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne, DM_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Builder Website",
  description: "Generated by create next app",
};

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {

//   const cookieStore = await cookies()
//   const sidebarState = cookieStore.get("sidebar_state")?.value;

//   // buka HANYA kalau cookie-nya bernilai "true"
//   const defaultOpen = sidebarState === "true";
//   return (
//     <html lang="en">
//       <head></head>
//       <body>
//         <NavBarMenu />
//         <SidebarProvider defaultOpen={defaultOpen}>
//           <AppSidebar />
//           {children}
//         </SidebarProvider>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${syne.variable} ${dmSans.variable}`}>{children}</body>
    </html>
  );
}
